#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-library
Version  : 1
Release  : 3
URL      : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
Source0  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
Source1  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.3/scala-library-2.10.3.pom
Source2  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
Source3  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.pom
Source4  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom
Source5  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
Source6  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.pom
Source7  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar
Source8  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom
Source9  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar
Source10  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.pom
Source11  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar
Source12  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom
Source13  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar
Source14  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.pom
Source15  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar
Source16  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: mvn-scala-library-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scala-library package.
Group: Data

%description data
data components for the mvn-scala-library package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.3/scala-library-2.10.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.3/scala-library-2.10.3.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
