#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scala-library
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
Source0  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
Source1  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom
Source2  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar
Source3  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom
Source4  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar
Source5  : https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: mvn-scala-library-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scala-library package.
Group: Data

%description data
data components for the mvn-scala-library package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar
/usr/share/java/.m2/repository/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom
